### ISSUE TITLE
Getting User Topics from the API fails periodically

### ISSUE THREAD

**Issue by jchate6** [LCOGT/hermes#50]
Sometimes when trying to get writable user topics from the API, we get an error.

This doesn't happen every time, but only sometimes, making it very difficult to pin down.

**Comment by jchate6** [comment]
```Traceback (most recent call last):
  File "/home/jchatelain/test_tom/mytom/manage.py", line 22, in <module>
    main()
  File "/home/jchatelain/test_tom/mytom/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/jchatelain/test_tom/tom_env/lib64/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/jchatelain/test_tom/tom_env/lib64/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/jchatelain/test_tom/tom_env/lib64/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/jchatelain/test_tom/tom_env/lib64/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/jchatelain/test_tom/tom_env/lib64/python3.10/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/home/jchatelain/test_tom/tom_env/lib64/python3.10/site-packages/django/core/management/commands/migrate.py", line 100, in handle
    self.check(databases=[database])
  File "/home/jchatelain/test_tom/tom_env/lib64/python3.10/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/home/jchatelain/test_tom/tom_env/lib64/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/jchatelain/test_tom/tom_env/lib64/python3.10/site-packages/django/contrib/admin/checks.py", line 78, in check_dependencies
    for engine in engines.all():
  File "/home/jchatelain/test_tom/tom_env/lib64/python3.10/site-packages/django/template/utils.py", line 94, in all
    return [self[alias] for alias in self]
  File "/home/jchatelain/test_tom/tom_env/lib64/python3.10/site-packages/django/template/utils.py", line 94, in <listcomp>
    return [self[alias] for alias in self]
  File "/home/jchatelain/test_tom/tom_env/lib64/python3.10/site-packages/django/template/utils.py", line 85, in __getitem__
    engine = engine_cls(params)
  File "/home/jchatelain/test_tom/tom_env/lib64/python3.10/site-packages/django/template/backends/django.py", line 24, in __init__
    options["libraries"] = self.get_templatetag_libraries(libraries)
  File "/home/jchatelain/test_tom/tom_env/lib64/python3.10/site-packages/django/template/backends/django.py", line 42, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "/home/jchatelain/test_tom/tom_env/lib64/python3.10/site-packages/django/template/backends/django.py", line 116, in get_installed_libraries
    return {
  File "/home/jchatelain/test_tom/tom_env/lib64/python3.10/site-packages/django/template/backends/django.py", line 116, in <dictcomp>
    return {
  File "/home/jchatelain/test_tom/tom_env/lib64/python3.10/site-packages/django/template/backends/django.py", line 105, in get_template_tag_modules
    for name in get_package_libraries(pkg):
  File "/home/jchatelain/test_tom/tom_env/lib64/python3.10/site-packages/django/template/backends/django.py", line 128, in get_package_libraries
    module = import_module(entry[1])
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jchatelain/git/tom_base/tom_dataproducts/templatetags/dataproduct_extras.py", line 20, in <module>
    from tom_dataproducts.forms import DataProductUploadForm, DataShareForm
  File "/home/jchatelain/git/tom_base/tom_dataproducts/forms.py", line 39, in <module>
    DESTINATION_OPTIONS = get_sharing_destination_options()
  File "/home/jchatelain/git/tom_base/tom_dataproducts/forms.py", line 25, in get_sharing_destination_options
    destination_topics = get_hermes_topics()
  File "/home/jchatelain/git/tom_base/tom_dataproducts/alertstreams/hermes.py", line 138, in get_hermes_topics
    topics = response.json()['writable_topics']
  File "/home/jchatelain/test_tom/tom_env/lib64/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
